// Code generated by sql2gorm. DO NOT EDIT.
package model


type Purchase struct {
	TransID    string    `gorm:"column:trans_id;type:varchar(20);"`
	Status     string	 `gorm:"column:status; NOT NULL"`
	AddressId   int       `gorm:"column:address;type:int(11);NOT NULL"`
	Address 	Address
	Cars       int       `gorm:"column:cars;type:int(11)"`
	TotalPrice float64   `gorm:"column:total_price;type:double;NOT NULL"`
	CustomerID   int       `gorm:"column:customer;type:int(11);NOT NULL"`
	Customer 	Customer
}

